### ISSUE TITLE
Undo implementation

### ISSUE THREAD

**Issue by nidoro** [jakubfiala/atrament#71] opened 2021-05-25 19:32 UTC
Hello,
I'm getting unexpected results from my undo implementation. This is how I'm doing it:

**1. Initialize (global) empty array of strokes:**
`let strokes = []`

**2. When `strokerecorded` is fired, push stroke to array:**
```
atrament.addEventListener('strokerecorded', function(obj) {
    if (!atrament.recordPaused) {
        strokes.push(obj.stroke);
    }
});
```

**3. When the undo button is pressed, do the following:**
```
function undoStroke() {
    strokes.pop();
    atrament.clear();
    atrament.recordPaused = true;
    for (let stroke of strokes) {
        // set drawing options
        atrament.mode = stroke.mode;
        atrament.weight = stroke.weight;
        atrament.smoothing = stroke.smoothing;
        atrament.color = stroke.color;
        atrament.adaptiveStroke = stroke.adaptiveStroke;

        // don't want to modify original data
        const points = stroke.points.slice();

        const firstPoint = points.shift();
        // beginStroke moves the "pen" to the given position and starts the path
        atrament.beginStroke(firstPoint.x, firstPoint.y);

        let prevPoint = firstPoint;
        while (points.length > 0) {
            const point = points.shift();

            // the `draw` method accepts the current real coordinates
            // (i. e. actual cursor position), and the previous processed (filtered)
            // position. It returns an object with the current processed position.
            const { x, y } = atrament.draw(point.x, point.y, prevPoint.x, prevPoint.y);

            // the processed position is the one where the line is actually drawn to
            // so we have to store it and pass it to `draw` in the next step
            prevPoint = { x, y };
        }

        // endStroke closes the path
        atrament.endStroke(prevPoint.x, prevPoint.y);
    }
    atrament.recordPaused = false;
}
```

But this is what I get:
![Peek 2021-05-25 16-15](https://user-images.githubusercontent.com/21699304/119557154-33560c80-bd76-11eb-9f90-a5d4658a8bc9.gif)

Notice how after I press undo, the last line disappears, as expected, but the other two lines are extended a little bit.

Can you help me with this?
I'm on Linux. This happens on both Firefox 72.0.1 and Google Chrome 89.0.4389.90.

Thank you for the library!

**Comment by jakubfiala** [comment] 2022-05-14 08:59
@nidoro thank you for submitting the issue! Apologies for only getting to this now, I haven't been able to dedicate time to this lib for a while. I'll test your use case, try to reproduce the bug and fix it in the next few weeks.

**Comment by feored** [comment] 2022-08-14 01:20
Thanks for this example @nidoro . I modified it slightly to add support for fills, and fixed a few things that I assume have changed since your post (Point.point.x instead of point.x, ...). Not battle tested or anything but might save someone else a bit of trouble.

```
        this.sketchpad.addEventListener('strokerecorded', (obj) => {
            if (!this.sketchpad.recordPaused) {
                obj.stroke.type = "stroke";
                this.strokes.push(obj.stroke);
            }
        });

        this.sketchpad.addEventListener('fillstart', ({ x, y }) => {
            var obj = {};
            obj.type = "fill";
            obj.fillColor = this.sketchpad.color;
            obj.x = x;
            obj.y = y;
            this.strokes.push(obj);
        });


```


```
undo(){
            this.strokes.pop();
            this.sketchpad.clear();
            this.sketchpad.recordPaused = true;
            for (let stroke of this.strokes) {
                if (stroke.type == "stroke"){
                    // set drawing options
                    this.sketchpad.mode = stroke.mode;
                    this.sketchpad.weight = stroke.weight;
                    this.sketchpad.smoothing = stroke.smoothing;
                    this.sketchpad.color = stroke.color;
                    this.sketchpad.adaptiveStroke = stroke.adaptiveStroke;

                    // don't want to modify original data
                    const points = stroke.points.slice();

                    const firstPoint = points.shift().point;
                    // beginStroke moves the "pen" to the given position and starts the path
                    this.sketchpad.beginStroke(firstPoint.x, firstPoint.y);

                    let prevPoint = firstPoint;
                    while (points.length > 0) {
                        const point = points.shift();

                        // the `draw` method accepts the current real coordinates
                        // (i. e. actual cursor position), and the previous processed (filtered)
                        // position. It returns an object with the current processed position.
                        const { x, y } = this.sketchpad.draw(point.point.x, point.point.y, prevPoint.x, prevPoint.y);

                        // the processed position is the one where the line is actually drawn to
                        // so we have to store it and pass it to `draw` in the next step
                        prevPoint = { x, y };
                    }

                    // endStroke closes the path
                    this.sketchpad.endStroke(prevPoint.x, prevPoint.y);
                } else {
                    //setTimeout(() => {console.log("filling");this.sketchpad._floodFill(stroke.x, stroke.y, stroke.color); }, 100);
                    this.sketchpad.color = stroke.fillColor;
                    const startColor = Array.from(this.sketchpad.context.getImageData(stroke.x, stroke.y, 1, 1).data);
                    this.sketchpad._floodFill(stroke.x, stroke.y, startColor);
                }
                
            }
            this.sketchpad.recordPaused = false;
        }

```

**Comment by jakubfiala** [comment] 2024-01-18 18:20
@nidoro I may be nearly 3 years late, but I believe this bug has now been fixed :) it looks like the stroke segments recorded when `beginStroke` and `endStroke` are called were redundant. Specifically the segment recorded during `endStroke` caused the re-drawn stroke to be slightly longer than the original.

I am now working on a big update which will be released as v4 in the next few weeks. This fix will be part of it.

Thank you again for the bug report and apologies for being very, very late!

**Closed by jakubfiala** 2024-01-18 18:20 UTC
Labels: bug

**Comment by nidoro** [comment] 2024-01-18 20:12
Hi @jakubfiala, no need for apologies, that's the nature of open source. I'm currently not using atrament in any of my projects, but it's good to know that, if I ever need it, this will be fixed. Thank a lot!

**Comment by Innders** [comment] 2024-12-11 12:32
@feored This works pretty well but there is one things that might trip some people up.

The redraw loop will set the brush style for each undo and redo which is correct but then it will leave the brush style in that state when you next go to draw again. 

Maybe this is a feature not a bug but you will most likely want to restore the original brush styles to what they were when you started redrawing the history.

Here is my implementation...

```tsx
 // Store original brush settings
      const original = {
        mode: annotations.mode,
        weight: annotations.weight,
        smoothing: annotations.smoothing,
        color: annotations.color,
        adaptiveStroke: annotations.adaptiveStroke,
      };

      annotations.clear();
      annotations.recordPaused = true;

      const history = historyMap.get(pageNumber) || [];

      // Replay all strokes up to the target index
      for (let i = 0; i <= targetIndex; i++) {
        const stroke = history[i];
        if (!stroke?.segments?.length) continue;

        // Set stroke properties
        annotations.mode = stroke.mode;
        annotations.weight = stroke.weight;
        annotations.smoothing = stroke.smoothing;
        annotations.color = stroke.color;
        annotations.adaptiveStroke = stroke.adaptiveStroke;

        // Create a copy of segments to avoid modifying original data
        const segments = [...stroke.segments];
        const firstPoint = segments.shift().point;
        annotations.beginStroke(firstPoint.x, firstPoint.y);

        let prevPoint = firstPoint;
        while (segments.length > 0) {
          const point = segments.shift().point;
          const { x, y } = annotations.draw(
            point.x,
            point.y,
            prevPoint.x,
            prevPoint.y
          );
          prevPoint = { x, y };
        }

        annotations.endStroke(prevPoint.x, prevPoint.y);
      }

      annotations.recordPaused = false;

      // Restore original brush settings
      // timeout because it breaks without?!
      setTimeout(() => {
        annotations.mode = original.mode;
      }, 100);
      annotations.weight = original.weight;
      annotations.smoothing = original.smoothing;
      annotations.color = original.color;
      annotations.adaptiveStroke = original.adaptiveStroke;
      ``` 

Interestingly if the original mode was eraser and you undo a brush stroke it won't work properly unless the restoring of the mode is in a timeout, kind of weird, any ideas @jakubfiala ?

**Comment by jakubfiala** [comment] 2025-01-05 17:07
@Innders hmm that's odd, I can't think of a reason that would be necessary - Atrament doesn't execute any asynchronous code (other than passing messages between the fill worker and the main thread). Perhaps there's some other code in your application that updates the mode?

**Comment by AloidTech** [comment] 2026-08-27 19:39
If a line you draw overlaps with another and you undo it erases the line under it too, I think this is the flaw of this erasing method.
